import { useEffect, useState } from 'react';
import { PhoneCall, SkipForward, CheckCircle2 } from 'lucide-react';
import { completedQueueSeed, queueSeed } from '../../data/doctorSeed';
import { loadState, saveState, nowTime } from '../../utils/storage';
import { Badge, Button, Card, PageHeader } from '../../components/doctor/DoctorUI';

export default function DoctorQueue(){
 const [queue,setQueue]=useState(()=>loadState('doctor-queue',queueSeed)); const [done,setDone]=useState(()=>loadState('doctor-done-queue',completedQueueSeed));
 useEffect(()=>saveState('doctor-queue',queue),[queue]); useEffect(()=>saveState('doctor-done-queue',done),[done]);
 const current=queue.find(q=>q.status==='In Progress'); const waiting=queue.filter(q=>q.status==='Waiting');
 const callNext=()=>{ if(current)return alert('Finish or skip current patient first'); const next=waiting[0]; if(!next)return alert('No waiting patients'); setQueue(queue.map(q=>q.id===next.id?{...q,status:'In Progress'}:q)); };
 const markDone=()=>{ if(!current)return alert('No current patient'); setDone([{id:current.id,number:current.number,patient:current.patient,completed_at:nowTime()},...done]); setQueue(queue.filter(q=>q.id!==current.id)); };
 const skip=()=>{ if(!current)return; setQueue(queue.map(q=>q.id===current.id?{...q,status:'Waiting',priority:99}:q).sort((a,b)=>a.priority-b.priority)); };
 return <div><PageHeader title="My Queue" subtitle="Manage your patient queue" />
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><Stat title="In Progress" value={current?1:0}/><Stat title="Waiting" value={waiting.length}/><Stat title="Completed Today" value={done.length}/><Stat title="Avg Wait Time" value="28 min"/></div>
 <Card className="mb-6 border-teal-300 dark:border-teal-800 overflow-hidden"><div className="bg-teal-50 dark:bg-teal-500/10 p-5 flex justify-between"><h2 className="font-bold">Current Patient</h2><Badge tone="blue">{current?'In Progress':'None'}</Badge></div><div className="p-5 md:p-8 flex flex-col md:flex-row md:items-center justify-between gap-5">{current?<div className="flex items-center gap-5"><div className="w-20 h-20 rounded-2xl bg-teal-100 text-teal-700 grid place-items-center font-bold text-xl">{current.number}</div><div><h3 className="text-xl font-bold">{current.patient}</h3><p className="text-sm text-slate-500">Started {current.waiting} min ago · Priority: {current.priority}</p></div></div>:<p className="text-slate-500">No patient currently in progress.</p>}<div className="flex gap-3"><Button variant="green" disabled={!current} onClick={markDone}><CheckCircle2 size={16} className="inline mr-2"/>Mark as Done</Button><Button variant="outline" disabled={!current} onClick={skip}><SkipForward size={16} className="inline mr-2"/>Skip</Button></div></div></Card>
 <div className="grid lg:grid-cols-2 gap-6"><Card className="p-5"><div className="flex justify-between mb-5"><h2 className="font-bold">Upcoming Queue ({waiting.length})</h2><Button onClick={callNext}><PhoneCall size={16} className="inline mr-2"/>Call Next</Button></div><div className="space-y-3">{waiting.map(q=><QueueItem key={q.id} q={q}/>)}</div></Card><Card className="p-5"><h2 className="font-bold mb-5">Completed Today ({done.length})</h2><div className="space-y-3">{done.map(q=><div key={q.id} className="bg-slate-50 dark:bg-slate-800 p-4 rounded-xl flex justify-between"><div className="flex gap-3"><div className="w-12 h-12 rounded-xl bg-green-100 text-green-700 grid place-items-center font-bold">{q.number}</div><div><p className="font-bold">{q.patient}</p><p className="text-sm text-slate-500">Completed at {q.completed_at}</p></div></div><Badge tone="green">Completed</Badge></div>)}</div></Card></div>
 </div>
}
function Stat({title,value}){return <Card className="p-5"><p className="text-sm text-slate-500">{title}</p><p className="text-2xl font-bold mt-2">{value}</p></Card>}
function QueueItem({q}){return <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-xl flex justify-between"><div className="flex gap-3"><div className="w-12 h-12 rounded-xl bg-yellow-100 text-yellow-700 grid place-items-center font-bold">{q.number}</div><div><p className="font-bold">{q.patient}</p><p className="text-sm text-slate-500">Waiting: {q.waiting} min</p></div></div><div className="text-right"><Badge tone="yellow">Waiting</Badge><p className="text-xs text-slate-500 mt-2">Priority: {q.priority}</p></div></div>}
